- name: Install MariaDB packages
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Start MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
