---
# tasks file for firewall
- name: Install firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Start and enable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

